### ISSUE TITLE
Handle eslint error on npm run start

### ISSUE THREAD

**Issue by wood-crafter** [wood-crafter/my-tinder#36]

**Comment by wood-crafter** [comment]
@hoangph271 
Please work on this issue

**Comment by hoangph271** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/39024711/183893406-67b26315-2104-407b-b505-a006f17aae63.png">

@wood-crafter I don't see any issue here...?

**Comment by wood-crafter** [comment]
@hoangph271 
Eslin show warning when i first start!
If you dont have this problem, i'll work on it

**Comment by hoangph271** [comment]
@wood-crafter dude it's ESLint.

I think this can be resolved when we land the merge for #33...!
So leave this alone and focus on #33...!
