### ISSUE TITLE
eslint failed on npm run start

### ISSUE THREAD

**Issue by wood-crafter** [wood-crafter/my-tinder#44]
![image](https://user-images.githubusercontent.com/59172319/187139871-1b91ff31-d6e6-4a38-83e1-e235ebba6b1c.png)
I got this on start page. Please fix and tell me how

**Comment by hoangph271** [comment]
@wood-crafter remove node_modules and install again.

**Comment by wood-crafter** [comment]
> @wood-crafter remove node_modules and install again.

@hoangph271  
Better tell me after implemented
